### PR TITLE
Local development instructions

### PR DESCRIPTION
**Pull request by MylesBorins**
Added some documentation to help people get started with development. ~~Also added `book.json` to the gitignore~~

### CODE REVIEW

**Comment by MylesBorins** [comment]
It would appear adding `book.json` to the gitignore breaks gitbook... fun!

We may want to check it into the repo

**Comment by mikesamuel** [comment]
README.md is currently the front page of the book.

Do you mean to put these instructions above the abstract?

If you want a README.md that is separate from the book content, we can rename README.md to cover.md and change SUMMARY.md to point to that instead.

**Comment by mikesamuel** [comment]
> It would appear adding book.json to the gitignore breaks gitbook... fun!

Yeah :) sigh
.bookignore inherits all of .gitignore.

**Comment by mikesamuel** [comment]
Fyi, `make` dumps some useful help info:

https://github.com/google/node-sec-roadmap/blob/2264778ca2430863fc19d5f97a81ed030c10fe61/Makefile#L6-L31

**Comment by MylesBorins** [comment]
As I was digging through to try and make the repo more discoverable I figured out that the README.md is the main page. I've moved the instruction to CONTRIBUTING.md but perhaps we should do what you suggested and make an explicit Cover that is different from the README

**Comment by mikesamuel** [comment]
>  make an explicit Cover that is different from the README

will do

**Comment by mikesamuel** [comment]
Please see https://github.com/google/node-sec-roadmap/commit/ffbadeba8a282205bf17e5d9e7fa369af4f2714b and the new [README](https://github.com/google/node-sec-roadmap/blob/master/README.md).

**Comment by MylesBorins** [comment]
Closing, new documentation looks awesome!

**Pull request closed without merging**
