### PR TITLE
Fix link to hydra worm disclosure document

### PR DESCRIPTION
**Pull request by MarcinHoppe**
The link to the document was broken, this one is working.

### CODE REVIEW

**Comment by MarcinHoppe** [comment]
I signed it!

**Comment by mikesamuel** [comment]
Thanks much. Is vince-uploaded a suborigin you control?

**Comment by MarcinHoppe** [comment]
No, I just happened to find it there, I am not even sure it works anymore.

I was cleaning up my open PRs and I somewhat assumed this would not get merged, hence my decision to close it without merging.

**Comment by mikesamuel** [comment]
Sorry, for some reason I didn't notice this when it went past.  But it floated up when you closed it.  Will try to find a better way to link that.

**Comment by MarcinHoppe** [comment]
Thanks! Do you want me to reopen the PR?

**Pull request closed without merging**
