### PR TITLE
Added a top-bar button that links to the GitHub repo

### PR DESCRIPTION
**Pull request by mikesamuel**
Addresses https://github.com/google/node-sec-roadmap/issues/15

### CODE REVIEW

**Comment by mikesamuel** [comment]
The GitHub logo comes from https://github.com/logos which explicitly allows its use for linking to GitHub.

**Comment by MylesBorins** [comment]
Mostly looks good. Since the github logo is a direct link it is now resizing on hover, which is inconsistent with the other buttons

**Comment by mikesamuel** [comment]
I'm guessing that's related to some :hover default gitbook styles.

**Comment by MylesBorins** [comment]
Following diff fixes it

```
diff --git a/styles/website.css b/styles/website.css
index a9f02de..81c790a 100644
--- a/styles/website.css
+++ b/styles/website.css
@@ -26,12 +26,13 @@

 .github-button.btn.links-link {
     display: inline-block;
-    width: 32px;
+    width: 30px;
     font-size: 0;
     background-image: url("/images/GitHub-Mark-32px.png");
     background-repeat: no-repeat;
     background-position: center center;
     opacity: 0.25;
+    background-size: 20px;
 }
```

**Comment by mikesamuel** [comment]
Folded your fix into this PR.  Thanks.

**Pull request merged**
